package mtree

import (
	"bufio"
	"fmt"
	"io"
	"io/fs"
	"path"
	"sort"
	"strings"

	"github.com/emmanuel-deloget/fsforge/pkg/image"
)

// Write emits a specification describing root, in the 2.0 dialect: one full
// path per line, no directory nesting to track. It is the dialect libarchive
// writes and the easier of the two to diff, which is most of what a spec of an
// existing image is for.
//
// Entries are sorted by path, so the same tree yields the same bytes.
func Write(w io.Writer, root *image.Node) error {
	bw := bufio.NewWriter(w)
	fmt.Fprintln(bw, "#mtree")
	fmt.Fprintln(bw, "# Generated by fsforge.")

	if err := writeEntry(bw, ".", root); err != nil {
		return err
	}
	if err := walk(bw, root, ""); err != nil {
		return err
	}
	return bw.Flush()
}

func walk(w *bufio.Writer, n *image.Node, prefix string) error {
	kids := append([]image.Entry(nil), n.Children...)
	sort.Slice(kids, func(i, j int) bool { return kids[i].Name < kids[j].Name })
	for _, e := range kids {
		p := path.Join(prefix, e.Name)
		if err := writeEntry(w, "./"+p, e.Node); err != nil {
			return err
		}
		if e.Node.IsDir() {
			if err := walk(w, e.Node, p); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeEntry(w *bufio.Writer, p string, n *image.Node) error {
	t := typeOf(n.Mode)
	fields := []string{
		vis(p),
		"type=" + t.String(),
		fmt.Sprintf("mode=%04o", unixFromPerm(n.Mode)),
		fmt.Sprintf("uid=%d", n.UID),
		fmt.Sprintf("gid=%d", n.GID),
	}
	if !n.ModTime.IsZero() {
		fields = append(fields, fmt.Sprintf("time=%d.%09d", n.ModTime.Unix(), n.ModTime.Nanosecond()))
	}
	switch t {
	case TypeLink:
		fields = append(fields, "link="+vis(n.Link))
	case TypeBlock, TypeChar:
		fields = append(fields, fmt.Sprintf("device=native,%d,%d", n.Rdev>>8, n.Rdev&0xFF))
	case TypeFile:
		if n.Content != nil {
			fields = append(fields, fmt.Sprintf("size=%d", n.Content.Size()))
		}
	}
	for _, k := range sortedKeys(n.Xattrs) {
		fields = append(fields, "xattr."+k+"="+vis(string(n.Xattrs[k])))
	}
	_, err := fmt.Fprintln(w, strings.Join(fields, " "))
	return err
}

func sortedKeys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// vis escapes a value the way mtree expects: whitespace, backslashes, the
// keyword separator and anything unprintable become octal escapes, so a
// filename with a space in it survives a round trip through the format.
func vis(s string) string {
	var out strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\\':
			out.WriteString(`\\`)
		case c <= ' ' || c >= 0x7f || c == '=' || c == '#':
			fmt.Fprintf(&out, `\%03o`, c)
		default:
			out.WriteByte(c)
		}
	}
	return out.String()
}

// FromDir is the other direction from the host: a specification describing a
// directory as it stands. It is what makes a spec maintainable — generate one,
// edit the ownership, keep it in the repository.
func FromDir(w io.Writer, dir string) error {
	root, err := scan(dir)
	if err != nil {
		return err
	}
	return Write(w, root)
}

func scan(dir string) (*image.Node, error) {
	root := &image.Node{Nlink: 2}
	root.Mode = fs.ModeDir | 0o755
	err := walkHost(dir, root)
	return root, err
}
